name: "MyAnimeList"
guid: "ed04e975-f906-4b58-a250-705550810623"
version: 1
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "MyAnimeList metadata provider"
description: >
  MyAnimeList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.MyAnimeList.dll"
changelog: |-
