<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MyAnimeList</RootNamespace>
    
    <Version>6.5.0.1</Version>
    <AssemblyVersion>6.5.0.1</AssemblyVersion>
    <FileVersion>6.5.0.1</FileVersion>

    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <IsPublishable>true</IsPublishable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <BaseOutputPath>C:\ProgramData\Jellyfin\Server\plugins\Jellyfin.Plugin.MyAnimeList</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FuzzierSharp" Version="3.0.1" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.6" />
    <PackageReference Include="JikanDotNet" Version="2.10.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
  </ItemGroup>

  <Target Name="CopyPluginDependencies" AfterTargets="Build">
    <ItemGroup>
      <PluginDeps Include="$(NuGetPackageRoot)fuzziersharp\*\lib\netstandard2.0\FuzzierSharp.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)jikandotnet\*\lib\netstandard2.0\JikanDotNet.dll" />
    </ItemGroup>

    <Copy
      SourceFiles="@(PluginDeps)"
      DestinationFolder="$(OutDir)" />
  </Target>

  <Target Name="CleanPluginDependencies" BeforeTargets="Clean">
    <ItemGroup>
      <PluginDeps Include="$(OutDir)FuzzierSharp.dll" />
      <PluginDeps Include="$(OutDir)JikanDotNet.dll" />
    </ItemGroup>

    <Delete Files="@(PluginDeps)" />
  </Target>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

</Project>
