<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MyAnimeList</RootNamespace>
    <Version>6.3.7</Version>
    <AssemblyVersion>6.3.7</AssemblyVersion>
    <FileVersion>6.3.7</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <BaseOutputPath>C:\ProgramData\Jellyfin\Server\plugins\Jellyfin.Plugin.MyAnimeList</BaseOutputPath>
    <Optimize>False</Optimize>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="JikanDotNet">
      <HintPath>..\..\jikan.net\JikanDotNet\bin\Debug\net8.0\JikanDotNet.dll</HintPath>
    </Reference>
    <Reference Include="JikanDotNet">
      <HintPath>..\..\FuzzierSharp\FuzzierSharp\bin\Debug\netstandard2.0\FuzzierSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
