<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MyAnimeList</RootNamespace>
    
    <Version>6.6.2.2</Version>
    <AssemblyVersion>6.6.2.2</AssemblyVersion>
    <FileVersion>6.6.2.2</FileVersion>

    <DebugType>none</DebugType>
    <IsPublishable>false</IsPublishable>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <BaseOutputPath>C:\ProgramData\Jellyfin\Server\plugins\Jellyfin.Plugin.MyAnimeList</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AnitomySharp.NET6" Version="0.5.1" />
    <PackageReference Include="FuzzierSharp" Version="3.0.1" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.8" />
    <PackageReference Include="JikanDotNet" Version="2.10.4" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
  </ItemGroup>

  <Target Name="CopyPluginDependencies" AfterTargets="Build">
    <ItemGroup>
      <PluginDeps Include="$(NuGetPackageRoot)fuzziersharp\*\lib\netstandard2.1\FuzzierSharp.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)jikandotnet\*\lib\net8.0\JikanDotNet.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)anitomysharp.net6\*\lib\net6.0\AnitomySharp.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)litedb\*\lib\netstandard2.0\LiteDB.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)messagepack\*\lib\net9.0\MessagePack.dll" />
      <PluginDeps Include="$(NuGetPackageRoot)messagepack.annotations\*\lib\netstandard2.0\MessagePack.Annotations.dll" />
    </ItemGroup>

    <Copy SourceFiles="@(PluginDeps)" DestinationFolder="$(OutDir)" />
  </Target>

  <Target Name="CleanPluginDependencies" BeforeTargets="Clean">
    <ItemGroup>
      <PluginDeps Include="$(OutDir)FuzzierSharp.dll" />
      <PluginDeps Include="$(OutDir)JikanDotNet.dll" />
      <PluginDeps Include="$(OutDir)AnitomySharp.dll" />
      <PluginDeps Include="$(OutDir)LiteDB.dll" />
      <PluginDeps Include="$(OutDir)MessagePack.dll" />
      <PluginDeps Include="$(OutDir)MessagePack.Annotations.dll" />
    </ItemGroup>

    <Delete Files="@(PluginDeps)" />
  </Target>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

</Project>
